#!/bin/bash

echo "Check dependencies..."
[ "$(dpkg -l | grep "^ii  make\|^ii  ansible" | wc -l)" != "2" ] \
	&& sudo apt install make ansible

echo "Check repository..."
[ ! -d ~/ansible ] \
	&& git clone http://www.github.com/pfsmorigo/ansible
